name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-format:
    name: Lint and Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Run go vet
        run: go vet ./...

      - name: Check formatting with gofmt
        run: gofmt -l -w .

      - name: Install gofumpt (for Go formatting)
        run: go install mvdan.cc/gofumpt@latest

      - name: Check formatting with gofumpt
        run: gofumpt -l -w .
